### PR TITLE
feat: add nonce manager

### PR DESCRIPTION
**Pull request by Sekhmet**
Closes: https://github.com/snapshot-labs/mana/issues/122
Depends on: https://github.com/snapshot-labs/sx.js/pull/247

### Test plan
- Run mana with sx.js linked
- Point to this mana instance on sx-ui.
- Create n proposals on some space (I just use simple space with Eth authenticator).
- Queue votes on all of those proposals at the same time (do not approve on Metamask).
- Once all queued up quickly confirm all signature requests.
- Everything should still work.

### CODE REVIEW

**Comment by bonustrack** [comment]
I'm not able to run this branch, I tried merged master because there was issues like importing StarkNetTx instead of StarknetTx. I can see current code have some others conflict issues, see missing import for this function here: https://github.com/snapshot-labs/mana/blob/75bb4734795c44a8c001acfc94fefe13e9fdf626/src/stark/index.ts#L21

**Comment by Sekhmet** [comment]
Rebased and released sx.js it depended on so should be testable out of the box.

**Comment by bonustrack** [comment]
Got this error now that make Mana crash:
```
error: select * from "registered_proposals" where "processed" = $1 - column "processed" does not exist
```

**Comment by Sekhmet** [comment]
You need to delete `registered_proposals` table as the schema changed. We don't have migrations so those don't change automatically. Before we used to just drop database on startup if it already existed, but that's not great solution, because on deploy we would lose persisted transactions/proposals.

**Comment by bonustrack** [comment]
I was able to test, I've made 4 proposals:

Proposal 1: where I have voting power, vote worked
Proposal 2: where I don't have voting power, vote failed
Proposal 3: I have voting power, failed
Proposal 4: I have voting power, failed

After proposal 2, Mana got stuck and couldn't do anymore transaction. I used the feed to cast a vote without voting power.

**Comment by Sekhmet** [comment]
@bonustrack should work now. It was issue caused by the fact we were caching Account (and NonceManager) per space-address instead of wallet index so when using two spaces it would not by in-sync.

**Comment by bonustrack** [comment]
I had a transaction rejected for a proposal where I have voting power: https://testnet.starkscan.co/tx/0x2f9f541c21b5faba42a73bcf1939cbdda3b3416d590bb76faf3493320e687d6 I tested the flow 3-4 times and was not able to reproduce, it might not be related to these changes, all others txs went through.

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
