### PR TITLE
chore: add goerli2 support

### PR DESCRIPTION
**Pull request by Sekhmet**
## Summary

Adds Goerli2 network support.

Environment variables need to be updated to use goerli2 Starknet account.

Might need to update `FOSSIL_ADDRESS` as well too
```
FOSSIL_ADDRESS=0x456Cb24d30eaA6AfFC2A6924Dae0d2a0a8c99C73
```

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
utACK

**Comment by bonustrack** [comment]
I've updated Mana `FOSSIL_ADDRESS` config var, but `STARKNET_PRIVKEY` and `STARKNET_ADDRESS` still use the Goerli 1 account so it wont work if you try, should I move it to the Goerli 2 account you shared previously in our chat?

**Comment by Sekhmet** [comment]
@bonustrack we can use that one, I don't know how to transfer funds out of it so I'm only using it to burn fees :D

**Comment by bonustrack** [comment]
@Sekhmet You should be able to load the account from Argent X to do a transfer. I can confirm I've changed the account on Mana

**Comment by Sekhmet** [comment]
@bonustrack it's no longer possible to import private key into ArgentX after some update (only seed) which CLI doesn't give.

**Pull request merged**
